name: Build and Push Docker Image

on:
  push:
    branches:
      - build  # Or specify your main branch name here

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t noscopev6/k8-todoapp:ci .
      
    - name: Push Docker image to Docker Hub
      run: docker push noscopev6/k8-todoapp:ci
